# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    ruby_task_helper:
      repo: "puppetlabs/ruby_task_helper"
      ref: "0.5.1"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
    node_manager:
      repo: "WhatsARanjit/node_manager"
    bolt_shim:
      repo: "puppetlabs/bolt_shim"
    apply_helpers:
      repo: "puppetlabs/apply_helpers"
    format:
      repo: "puppet/format"
  repositories:
    "stdlib":
      "repo": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "translate":
      "repo": "https://github.com/puppetlabs/puppetlabs-translate"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
    peadm: 'git://github.com/puppetlabs/puppetlabs-peadm'
